package com.jovial.AST;

import java.util.ArrayList;
import java.util.List;

/**
 * Minimal representation of a parsed Jovial source file.
 * <p>
 * The class currently only stores a list of top level functions.  A real
 * implementation would expose the full tree generated by the language server
 * including statements, expressions, types and source locations.
 * TODO: Replace this class with a proper model once the LSP parser is ready.
 */
public class ASTModel {

    private final List<FunctionNode> functions = new ArrayList<>();

    public List<FunctionNode> getFunctions() {
        return functions;
    }

    public void addFunction(FunctionNode fn) {
        functions.add(fn);
    }
}
