package com.jovial.AST;

import java.util.ArrayList;
import java.util.List;

/**
 * Root model of the abstract syntax tree used by the plugin. The current
 * implementation is deliberately small and hand crafted.  A real implementation
 * would be generated by the Jovial language server.
 */
public class ASTModel {

    private final List<FunctionNode> functions = new ArrayList<>();

    public List<FunctionNode> getFunctions() {
        return functions;
    }

    public void addFunction(FunctionNode fn) {
        functions.add(fn);
    }

    // TODO: add facilities for looking up nodes by position, retrieving global
    // variables, includes, etc. The final model should mirror the real Jovial
    // grammar once parsing through the LSP is available.
}
